apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: che1
  annotations:
    github.com/project-slug: debsmita1/che
spec:
  type: other
  lifecycle: unknown
  owner: group:default/team-a
